### ISSUE TITLE
Problem of the metrics in the paper

### ISSUE THREAD

**Issue by zw-SIMM** [GT4SD/multitask_text_and_chemistry_t5#1]
Nice work!
I have some problems of the metrics used in the table1, especially about the task of text2text(paragraph-actions).
You have mentioned that “For the forward prediction task the metric is accuracy; for the retrosynthesis task the metric is roundtrip accuracy (Schwaller et al., 2020); for all the other tasks the BLEU score.”
So what metric do you use in the task of text2text(paragraph-actions)? BLEU-2 or BLEU-4?

**Comment by christofid** [comment]
Hi @medicine-wave, we used BLEU-2 for the paragraph-to-actions task.

**Comment by zw-SIMM** [comment]
> Hi @medicine-wave, we used BLEU-2 for the paragraph-to-actions task.

OK, thanks, can you provide the code for easier evaluation?
Because I found the BLEU score metrics used in Paragraph2actions[2020 A.Vaucher] is corpus-bleu(bleu4), is there something different?

**Comment by christofid** [comment]
In Paragraph2actions[2020 A.Vaucher], they used a slightly [modified BLEU score](https://github.com/rxn4chemistry/paragraph2actions/blob/2a922a96d77cd796855fdf0322dc314351e29979/paragraph2actions/analysis.py#L64) while in our case we used the BLEU-2 metric as we stuck to the existing NLP metrics used also for the rest tasks of interest in this work. 

I attach the piece of code that we used to compute this metric. I will try to find some time to clean up and provide the whole evaluation script.
 
```
 from nltk.translate.bleu_score import corpus_bleu

  for gt, out in outputs:

      gt_tokens = [c for c in gt]

      out_tokens = [c for c in out]

      references.append([gt_tokens])
      hypotheses.append(out_tokens)

  bleu2 = corpus_bleu(references, hypotheses, weights=(.5, .5))
```

**Comment by zw-SIMM** [comment]
> In Paragraph2actions[2020 A.Vaucher], they used a slightly [modified BLEU score](https://github.com/rxn4chemistry/paragraph2actions/blob/2a922a96d77cd796855fdf0322dc314351e29979/paragraph2actions/analysis.py#L64) while in our case we used the BLEU-2 metric as we stuck to the existing NLP metrics used also for the rest tasks of interest in this work.
> 
> I attach the piece of code that we used to compute this metric. I will try to find some time to clean up and provide the whole evaluation script.
> 
> ```
>  from nltk.translate.bleu_score import corpus_bleu
> 
>   for gt, out in outputs:
> 
>       gt_tokens = [c for c in gt]
> 
>       out_tokens = [c for c in out]
> 
>       references.append([gt_tokens])
>       hypotheses.append(out_tokens)
> 
>   bleu2 = corpus_bleu(references, hypotheses, weights=(.5, .5))
> ```

Many thanks for your reply!
