### ISSUE TITLE
Problem of the finetuneing code

### ISSUE THREAD

**Issue by zw-SIMM** [GT4SD/multitask_text_and_chemistry_t5#2]
How to do with this problem? I put the demo finetune code into run.sh

(gt4sd) a100-5:~/multitask_text_and_chemistry_t5$ bash run.sh 

Traceback (most recent call last):
  File "xxx/anaconda3/envs/gt4sd/bin/gt4sd-trainer", line 8, in <module>
    sys.exit(main())
  File "xxx/anaconda3/envs/gt4sd/lib/python3.8/site-packages/gt4sd/cli/trainer.py", line 185, in main
    pipeline().train(**config)
TypeError: train() missing 3 required positional arguments: 'pl_trainer_args', 'model_args', and 'dataset_args'

**Comment by christofid** [comment]
Hi @medicine-wave, I am investigating this issue and trying to reproduce it. How did you install GT4SD? Did you try to install it directly via pip or you followed the suggested way using conda? Also which version of GT4SD have you installed? Thanks
