### ISSUE TITLE
Usage of ChEBI-20 Data Splits in Model Training

### ISSUE THREAD

**Issue by Sangyeup** [GT4SD/multitask_text_and_chemistry_t5#4]
Hello,

I'm curious about the data splits from the ChEBI-20 dataset that were used for training the huggingface model below. 
https://huggingface.co/GT4SD/multitask-text-and-chemistry-t5-base-augm

Were the test and validation sets included, or was the training set only?

Thanks for clarifying,
Sangyeup

**Comment by christofid** [comment]
Hi @Sangyeup, thanks for your interest! We used only the training set of ChEBI-20 during the training of our model, but note that in order to have the final training dataset balanced between tasks, we replicated each instance multiple times to reach the 2.3M samples for the respective tasks.

**Comment by Sangyeup** [comment]
Thanks for the fast answer! :)
